apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-srv-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets-srv
  template:
    metadata:
      labels:
        app: tickets-srv
    spec:
      containers:
        - name: tickets-srv
          image: liridonrama/tickets-srv
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: MONGO_URI
              value: mongodb://tickets-srv-mongo-srv:27017/tickets
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv-srv
spec:
  selector:
    app: tickets-srv
  ports:
    - name:
      protocol: TCP
      port: 3000
      targetPort: 3000
