name: deploy-manifest

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # use if you want to deploy to remote k8s cluster in digital ocean 
      # - uses: digitalocean/action-doctl@v2
      #   with:
      #     token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      # - run: doctl kubernetes cluster kubeconfig save k8s-1-21-9-do-0-fra1-1645560297151
      # - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
