name: deploy-auth

on:
  push:
    branches:
      - main
    paths:
      - 'ticketing-auth-service/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ticketing-auth-service && docker build -t liridonrama/ticketing-auth-service .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push liridonrama/ticketing-auth-service
