name: tests-auth

on:
  pull_request:
    paths:
      - 'ticketing-auth-service/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ticketing-auth-service && npm i && npm run test:ci
  
