
name: tests-tickets-srv

on:
  pull_request:
    paths:
      - 'tickets-srv/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd tickets-srv && npm i && npm run test:ci
  
