name: Tests

on:
  pull_request
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ticketing-auth-service && npm i && npm run test:ci
      - run: cd orders && npm i && npm run test:ci
      - run: cd tickets-srv && npm i && npm run test:ci
      - run: cd payments && npm i && npm run test:ci
